class Movie
{
  static List<Movie> getMovies() =>
      [
        Movie("Iron Man", "2008", "PG_13", "1 May 2008", "126 min",
            "Action, Sci-Fi", "Jon Favreau", "Mark FergusHawk, OstbyArt Marcum",
            "Robert Downey Jr.,Gwyneth Paltrow,Terrence Howard",
            "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
            "English, Hindi", "Nominated for 2 Oscars.22 wins & 73 nominations total",
            "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
            "79", "7.9", "1,100,000", "True",
            [
              "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTUzODkyNDE2OV5BMl5BanBnXkFtZTcwMzEzNTIzMw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTk3NzIwNTA3MF5BMl5BanBnXkFtZTcwMjUyNTIzMw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTczNzM5OTAyMF5BMl5BanBnXkFtZTcwNTEzNTIzMw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjY4MDk0OTQ2MF5BMl5BanBnXkFtZTcwNTgxNTIzMw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Iron Man 2", "2010", "PG_13", "7 May 2010", "124 min",
            "Action, Sci-Fi, Adventure", "Jon Favreau", "Justin TherouxStan LeeDon Heck",
            "Robert Downey Jr.Mickey RourkeGwyneth Paltrow",
            "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "Nominated for 1 Oscar.7 wins & 44 nominations total",
            "https://m.media-amazon.com/images/M/MV5BZGVkNDAyM2EtYzYxYy00ZWUxLTgwMjgtY2VmODE5OTk3N2M5XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_.jpg",
            "57", "6.9", "830,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMTY5MjU1ODQ5Ml5BMl5BanBnXkFtZTcwOTgwODYzMw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTI3NzYxMDEwNV5BMl5BanBnXkFtZTcwMTkxNzYyMw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTk0NjA4OTkyN15BMl5BanBnXkFtZTcwMjk4NDIzMw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTcxOTM4Njc4M15BMl5BanBnXkFtZTcwMDgxODMzMw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjE5MDA0MDEyMl5BMl5BanBnXkFtZTcwMDk4NDIzMw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
            ]),
        Movie("Iron Man 3", "2013", "PG_13", "26 april 2013", "130 min",
            "Action, Adventure, Sci-Fi", "Shane Black", "Drew Pearce,Shane Black,Stan Lee",
            "Robert Downey Jr.,Guy Pearce,Gwyneth Paltrow",
            "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "Nominated for 1 Oscar.20 wins & 63 nominations total",
            "https://cdn.marvel.com/content/1x/ironman3_lob_crd_01_10.jpg",
            "62", "7.1", "863,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjA2Nzk4NzU4OF5BMl5BanBnXkFtZTcwNTY3MDYwOQ@@._V1_UY100_CR68,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTc1MTQ5MzE1M15BMl5BanBnXkFtZTcwMTIxNjk3OA@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTYyMjYyNTMyMl5BMl5BanBnXkFtZTcwMzg4NTQ2OA@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTQ5NDQ1MDA1MV5BMl5BanBnXkFtZTcwODExNjk3OA@@._V1_UY100_CR70,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTQ4Njg0NTg4OV5BMl5BanBnXkFtZTcwNTg3MjAyOQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Thor", "2011", "PG_13", "2 May 2011", "115 min",
            "Action, Adventure, Sci-Fi", "Kenneth Branagh", "Ashley Miller,Zack Stentz,Don Payne",
            "Chris Hemsworth,Anthony Hopkins,Natalie Portman",
            "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "5 wins & 30 nominations",
            "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_.jpg",
            "57", "7.0", "862,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMTgzNDk2NTE3MF5BMl5BanBnXkFtZTcwNjc4MjIwNQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTA3MDQ2OTExNzZeQTJeQWpwZ15BbWU3MDI3ODIyMDU@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTY5Mjk1ODY1NV5BMl5BanBnXkFtZTcwNTY4MjIwNQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjIxNzc0NTYxNV5BMl5BanBnXkFtZTcwODY0ODQ5NA@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTQ0ODAwMzAwOF5BMl5BanBnXkFtZTcwMjc0ODQ5NA@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNzkyMDk3NzM5NF5BMl5BanBnXkFtZTcwNjg4MjIwNQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Thor Ragnarok", "2017", "PG_13", "3 Nov 2017", "125 min",
            "Action, Adventure, Comedy", "Taika Waititi", "Eric Pearson,Craig Kyle,Christopher L. Yost",
            "Chris HemsworthTom HiddlestonCate Blanchett",
            "A paralegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "6 wins & 49 nominations",
            "https://th.bing.com/th?id=OIP.W2jZ6C6P55L4RVq1h8zquAHaK-&w=205&h=304&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2",
            "74", "7.9", "768,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BNzkyMDk3NzM5NF5BMl5BanBnXkFtZTcwNjg4MjIwNQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTU1NjQyNTEzNV5BMl5BanBnXkFtZTgwNjAxMjgwNDI@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTU1NjQyNTEzNV5BMl5BanBnXkFtZTgwNjAxMjgwNDI@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjM5ODYyMDI4M15BMl5BanBnXkFtZTgwMzIxMjgwNDI@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjQ5OTk4NjIyNF5BMl5BanBnXkFtZTgwOTAxMjgwNDI@._V1_UY100_CR69,0,100,100_AL_.jpg",
            ]),
        Movie("Captain America: The First Avenger", "2011", "PG_13", "29 July 2011", "124 min",
            "Action, Adventure, Sci-Fi", "Joe Johnston", "Christopher Markus,Stephen McFeely,Joe Simon",
            "Chris Evans,Hugo Weaving,Samuel L. Jackson",
            "A paralegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "4 wins & 46 nominations",
            "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51wGo96+fpL.jpg",
            "66", "6.9", "858,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjQ5OTk4NjIyNF5BMl5BanBnXkFtZTgwOTAxMjgwNDI@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTcwNjM5NjY4NV5BMl5BanBnXkFtZTcwMjgwOTk5NQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTk0MDA2MTkxM15BMl5BanBnXkFtZTcwMDkwMDAwNg@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BOTY3OTYwNDI5N15BMl5BanBnXkFtZTcwNjMwOTk5NQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNTgwMDUxNDU5M15BMl5BanBnXkFtZTcwNjY3MTQ2NQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Captain America: Winter Soldier", "2013", "PG_13", "4 Apr 2013", "136 min",
            "Action, Adventure, Sci-Fi", "Anthony Russo,Joe Russo", "Christopher Markus,Stephen McFeely,Joe Simon",
            "Chris EvansSamuel L. JacksonScarlett Johansson",
            "A paralegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "Nominated for 1 Oscar.5 wins & 52 nominations total",
            "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/512BsbgYp6L.jpg",
            "70", "7.8", "860,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BNTgwMDUxNDU5M15BMl5BanBnXkFtZTcwNjY3MTQ2NQ@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjIzODY0NzA4NF5BMl5BanBnXkFtZTgwODQwMDM0MTE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjMwMDI3Mzg0M15BMl5BanBnXkFtZTgwNTQwMDM0MTE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTk5NTkzMzI2OV5BMl5BanBnXkFtZTgwNjMwMDM0MTE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTk0NDI5ODQwNV5BMl5BanBnXkFtZTgwMjIwMDM0MTE@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Captain America: Civil War", "2016", "PG_13", "6 May 2013", "147 min",
            "Action, Sci-Fi", "Anthony Russo,Joe Russo", "Christopher MarkusStephen McFeelyJoe Simon",
            "Chris EvansRobert Downey Jr.Scarlett Johansson",
            "A paralegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "16 wins & 73 nominations",
            "https://th.bing.com/th?id=OIP.ScvRDf41nfZYN9g7Bv0rsQHaLH&w=204&h=306&c=8&rs=1&qlt=30&o=6&dpr=1.5&pid=3.1&rm=2",
            "75", "7.8", "806,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjQwOTE1MDkyM15BMl5BanBnXkFtZTgwNzc5ODI2ODE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BODg3OTc4MTEyMl5BMl5BanBnXkFtZTgwODI0MDkyODE@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTkzNzExODQ0MV5BMl5BanBnXkFtZTgwNDI0MDkyODE@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjQwNzY5ODk4MF5BMl5BanBnXkFtZTgwMjI0MDkyODE@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTQ3ODQwMTQ0M15BMl5BanBnXkFtZTgwNjg5ODEyODE@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Black Panther", "2018", "PG_13", "14 Feb 2014", "134 min",
            "Action, Sci-Fi", "Ryan Coogler", "Ryan CooglerJoe Robert ColeStan Lee",
            "Chadwick BosemanMichael B. JordanLupita Nyong'o",
            "A paralegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            "English, Hindi", "Won 3 Oscars.117 wins & 282 nominations total",
            "https://th.bing.com/th?id=OIP.lOqONu1kA9GXn344kNnY-gHaK-&w=205&h=304&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2",
            "88", "7.3", "950,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjQyMDc0NTI0Ml5BMl5BanBnXkFtZTgwODE3MDM5NDM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMzU3MTM3MjQwN15BMl5BanBnXkFtZTgwOTI3MDM5NDM@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTg0MzU5MjYzNV5BMl5BanBnXkFtZTgwMTA3MDM5NDM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjQ2ODg2MTYyOV5BMl5BanBnXkFtZTgwNzg2MDM5NDM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTg5NzAzODM4MF5BMl5BanBnXkFtZTgwNTA3MDM5NDM@._V1_UY100_CR45,0,100,100_AL_.jpg",
            ]),
        Movie("Avengers", "2012", "PG_13", "27 Apr 2012", "143 min",
            "Action, Sci-Fi", "Joss Whedon", "Joss Whedon,Zak Penn",
            "Robert Downey Jr.,Chris Evans,Scarlett Johansson",
            "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
            "English, Hindi", "Nominated for 1 Oscar.38 wins & 80 nominations total",
            "https://th.bing.com/th?id=OIP.gbMJtCNw8QKH7bU8DdlsvQHaLH&w=204&h=306&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2",
            "69", "8.0", "1,400,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjE1MzEzMjcyM15BMl5BanBnXkFtZTcwNDM4ODY3Nw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNTAzNjk1MDE3NV5BMl5BanBnXkFtZTcwNDQ4ODY3Nw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjMwMzM2MTg1M15BMl5BanBnXkFtZTcwNjM4ODY3Nw@@._V1_UY100_CR39,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjA0NjY1MDM1M15BMl5BanBnXkFtZTcwODgwOTY3Nw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTUwNzc2NjczM15BMl5BanBnXkFtZTcwNTM3OTY3Nw@@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Doctor Strange", "2016", "PG_13", "4 Nov 2016", "115 min",
            "Action, Adventure, Fantasy", "Scott Derrickson", "Jon Spaihts,Scott Derrickson,C. Robert Cargill",
            "Benedict Cumberbatch,Chiwetel Ejiofor,Rachel McAdams",
            "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts",
            "English, Hindi", "Nominated for 1 Oscar.20 wins & 68 nominations total",
            "https://th.bing.com/th?id=OIP.jWNbAAaZlK0xrSHNzEQEEgDKEs&w=205&h=304&c=8&rs=1&qlt=30&o=6&dpr=1.5&pid=3.1&rm=2",
            "72", "7.5", "758,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjI0NTYyMzg4OV5BMl5BanBnXkFtZTgwNjQ5MDAzMDI@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTc0NDk0MjM1OF5BMl5BanBnXkFtZTgwMzY5MDAzMDI@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTU0MjY1MjM1MF5BMl5BanBnXkFtZTgwNTM5MDAzMDI@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTYwOTU5MzYzNV5BMl5BanBnXkFtZTgwMTM3MDM2NzE@._V1_UY100_CR26,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTgyMjUyNjA5OF5BMl5BanBnXkFtZTgwMjgwMzMyMDI@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Doctor Strange: Multiverse of Madness", "2022", "PG_13", "6 May 2022", "126 min",
            "Action, Adventure, Fantasy", "Sam Raimi", "Michael WaldronStan Lee,Steve Ditko",
            "Benedict Cumberbatch,Elizabeth Olsen,Chiwetel Ejiofor",
            "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.",
            "English, Hindi", "6 wins & 20 nominations",
            "https://cdn.marvel.com/content/1x/doctorstrangeinthemultiverseofmadness_lob_crd_02_3.jpg",
            "60", "6.9", "432,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BNTQxN2YxMzEtMGNlZC00ODkyLThlOTYtZWUwNjBlOTQwM2FjXkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_UX100_CR0,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BZmE1ZWMzOGMtMzg2OS00YzgzLWFhMDktYzE4YWEwN2Y0ZWVlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMzdiZTI5ZjMtZWE3OC00ZDJmLWJlYzUtODc0NDliYjgzYmU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BODJiMjNhMWEtMjc0Ni00YTFmLTljMWItYzFjNjFkYjUyMWYxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY100_CR69,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BYWJlZmYwMzQtNjViMy00MjVkLTkxZmQtYjMxZjdhZWVlYWU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY100_CR69,0,100,100_AL_.jpg",
            ]),
        Movie("Spider Man HomeComing", "2017", "PG_13", "7 July 2017", "133 min",
            "Action, Adventure, Sci-Fi", "Jon Watts", "Jonathan Goldstein,John Francis Daley,Jon Watts",
            "Tom Holland,Michael Keaton,Robert Downey Jr.",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "7 wins & 10 nominations",
            "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg",
            "73", "7.4", "672,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMTUwMjQwOTQzMl5BMl5BanBnXkFtZTgwOTcyMzM4MjI@._V1_UY100_CR70,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMzYzOTMzNDA5MV5BMl5BanBnXkFtZTgwNDcyMzM4MjI@._V1_UY100_CR70,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNzQzNTU5MzQ3OV5BMl5BanBnXkFtZTgwNTgyNjYxNDM@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMzQ5NjkzOTE0Ml5BMl5BanBnXkFtZTgwNjMzNTMzMjI@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjIwODIzNjQxOF5BMl5BanBnXkFtZTgwMjQyMzM4MjI@._V1_UY100_CR57,0,100,100_AL_.jpg",
            ]),
        Movie("Spider Man Far From Home", "2019", "PG_13", "2 July 2019", "129 min",
            "Action, Adventure, Comedy", "Jon Watts", "Chris McKenna,Erik Sommers,Stan Lee",
            "Tom Holland,Samuel L. Jackson,Jake Gyllenhaal",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "11 wins & 26 nominations",
            "https://upload.wikimedia.org/wikipedia/en/b/bd/Spider-Man_Far_From_Home_poster.jpg",
            "69", "7.4", "508,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjM3ZjM0YmMtYTkyZS00YzE0LThmZjgtNDNkN2NkNWJiOWJjXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BODY4OWU5MTUtMDJhYS00NjdmLTllMDgtNWI2Y2E2Yjg3ZWFkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR26,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjlmNzNjOTktM2U5ZS00MDc1LWE1MWYtM2E3MzdkZDU1M2YxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR29,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BM2NiZWY4YzItMzVmMi00MzRkLWI1NWYtODdhMTVmN2YyZmJlXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNTYwNjFlNzItNTRjOC00NTk3LWE0MDYtZGU4MWU0ZWM4NTQwXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Spider Man No Way Home", "2021", "PG_13", "17 Dec 2021", "148 min",
            "Action, Adventure, Fantasy", "Jon Watts", "Chris McKenna,Erik Sommers,Stan Lee",
            "Tom Holland,Zendaya,Benedict Cumberbatch",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "Nominated for 1 Oscar.35 wins & 69 nominations total",
            "https://cdn.marvel.com/content/1x/spider-mannowayhome_lob_crd_03.jpg",
            "78", "8.2", "782,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMWVmZDA2YjMtN2E3Yi00ZTQyLTkxMjAtMzI0NDVjM2E4ZmJlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY100_CR40,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BY2M2NjU2MjMtMDg4Yy00YWNhLWIzYzMtNWQxNDc1NzhjMzBiXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNDMyYTc5ZjYtZTUyNC00MDgxLWE1YTctNGUzOTkxNGE4NjAzXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_UX100_CR0,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BOGM5MzIwMjItMzljNy00NjczLThhNGMtZGNhNzhjNmQwMjM0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX100_CR0,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNGM0OWM4MDItNjk4Ny00OTE1LTljYWQtNDQyMjU5NTgyZmZiXkEyXkFqcGdeQXVyMTA2ODkwNzM5._V1_UX100_CR0,0,100,100_AL_.jpg",
            ]),
        Movie("Avengers Age of Ultron", "2015", "PG_13", "24 Apr 2015", "141 min",
            "Action, Adventure, Fantasy", "Joss Whedon", "Joss Whedon,Stan Lee,Jack Kirby",
            "Robert Downey Jr.,Chris Evans,Mark Ruffalo",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "8 wins & 52 nominations",
            "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/915mchBV+aL._SY606_.jpg",
            "66", "7.3", "878,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjExNzAxMzg0NV5BMl5BanBnXkFtZTgwNDg3MjQ0NDE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTkyODg2MjQ1MV5BMl5BanBnXkFtZTgwMDMwMjQ0NTE@._V1_UY100_CR70,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BODJmNWRmYzAtNTlmNC00NGI1LWJiZmEtOTBmMDY4OTMzYTk1XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTQ0MDU4NDY4Ml5BMl5BanBnXkFtZTgwNDM2NzYzMjE@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNTg1NDk5MDc5N15BMl5BanBnXkFtZTgwMzg3MjQ0NDE@._V1_UY100_CR25,0,100,100_AL_.jpg",
            ]),
        Movie("Avengers Infinity War", "2018", "PG_13", "27 Apr 2018", "149 min",
            "Action, Adventure, Sci-Fci", "Anthony Russo,Joe Russo", "Christopher Markus,Stephen McFeely,Stan Lee",
            "Robert Downey Jr.,Chris Evans,Mark Ruffalo",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "Nominated for 1 Oscar.46 wins & 79 nominations total",
            "https://cdn.marvel.com/content/1x/avengersinfinitywar_lob_mas_hlf_01_3.jpg",
            "68", "8.4", "1,100,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BMjA0MTg0MjUwMF5BMl5BanBnXkFtZTgwMjc4MjkzNTM@._V1_UY100_CR25,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTkzMTE1Mjk2Nl5BMl5BanBnXkFtZTgwMzk2MTUwNTM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTY2MjY0ODU1Nl5BMl5BanBnXkFtZTgwOTk2Njk5NDM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNzc1NTY4ODM1Nl5BMl5BanBnXkFtZTgwMjg4MjkzNTM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMjI1MTg0NjExOV5BMl5BanBnXkFtZTgwNzU4MjkzNTM@._V1_UY100_CR45,0,100,100_AL_.jpg",
            ]),
        Movie("Avengers Endgame", "2019", "PG_13", "26 Apr 2019", "181 min",
            "Action, Adventure, Drama", "Anthony Russo,Joe Russo", "Christopher Markus,Stephen McFeely,Stan Lee",
            "Robert Downey Jr.,Chris Evans,Mark Ruffalo",
            "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
            "English, Hindi", "Nominated for 1 Oscar.70 wins & 133 nominations total",
            "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQA_-tL18_rj9zEcjN6n41NEaJm-kRNF9UeOtvksZ4z_OW6jRA9",
            "78", "8.4", "1,200,000", "True",
            [
              "https://m.media-amazon.com/images/M/MV5BNDQ1YjBkNGEtYzUxZi00NzUyLTgwZGUtYmFhZTkzYTJkOTk0XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTJlNjEwODgtMDdiNy00ZDE1LWEwZTQtZjM2ZTYwYzkzY2M0XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BNTRmNDEzOTAtOGI0Yi00N2U1LTlhNDctNmQxMGFiNjk3ZmU4XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BMTYwMTUwNTAyOV5BMl5BanBnXkFtZTgwMTk1OTU5NzM@._V1_UY100_CR45,0,100,100_AL_.jpg",
              "https://m.media-amazon.com/images/M/MV5BOWQ0NmJlN2QtOTVjNi00YTY3LWE0MDUtOTlhMWFkZTA1MjExXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UY100_CR45,0,100,100_AL_.jpg",
            ]),
      ];
  late String title;
  late String year;
  late String rated;
  late String released;
  late String runtime;
  late String genre;
  late String director;
  late String writer;
  late String actors;
  late String plot;
  late String language;
  late String awards;
  late String poster;
  late String metascore;
  late String imdbRating;
  late String imdbVotes;
  late String response;
  late List<String> images;
  Movie(this.title, this.year, this.rated, this.released, this.runtime,
      this.genre, this.director,this.writer, this.actors, this.plot,
      this.language, this.awards, this.poster, this.metascore,
      this.imdbRating, this.imdbVotes,this.response,
      this.images);
}








